### PR TITLE
add goals and stuff to readme

### PR DESCRIPTION
**Pull request by tbuckl**
so that we can talk about what the goal of the repo is

@bobbylu this is an example of a master to master pull request across our account repositories

### CODE REVIEW

**Comment by tbuckl** [comment]
@bobbylu feel free to merge it into your repository if you want!

**Comment by tbuckl** [comment]
@bobbylu we can also talk more friday

**Comment by bobbylu** [comment]
@tombuckley so you cloned my master branch, and made a pull request in that branch?

**Comment by tbuckl** [comment]
yup!

**Pull request merged**
